name: CI/CD Pipeline
on:
  push:
    branches: [ main, staging ]
    paths:
      - 'web/**'
permissions:
  issues: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Clean Destination Directory
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            rm -rf ./prod
          else
            rm -rf ./* !./prod
            mkdir -p ./prod
          fi
        working-directory: ./gh-pages
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          destination_dir: ${{ github.ref_name == 'staging' && '' || 'prod' }}
          force_orphan: false

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment failed! Check the logs for details."
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments -d '{"body":"⚠️ Deployment failed! Please check the workflow logs."}'