name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # Add Permission
      contents: write  # Permiso to write in repo

    steps:      # Paso 1: Download code
      - name: Checkout Code
        uses: actions/checkout@v4
                # Paso 2: Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./