name: Daily Cleanup
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create Temporary File
        run: echo "This is a temp file" > temp.txt
      - name: Commit Temporary File
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add temp.txt
          git commit -m "Add temporary file for testing cleanup"
          git push
      - name: Clean Temporary Files
        run: |
          rm -f temp.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Cleanup: Remove temporary files"
          git push