name: Preview Site
on:
  workflow_dispatch:
permissions:
  issues: write
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Show HTML Content
        run: cat index.html
      - name: Comment Preview Link
        run: |
          echo "Preview your site content above. If it looks good, proceed with deployment."
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments -d '{"body":"🎉 Preview completed! Check the workflow logs to see the site content."}'